apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: my-workbench
  namespace: ml
  labels:
    app.kubernetes.io/instance: mlops-demo
spec:
  template:
    spec:
      serviceAccountName: my-workbench
      containers:
      - name: my-workbench
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/jupyter-minimal-cuda-py312-ubi9:2025.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 4Gi
        ports:
        - containerPort: 8888
          name: notebook-port
        volumeMounts:
        - name: workbench-pvc
          mountPath: /opt/app-root/src
      volumes:
      - name: workbench-pvc
        persistentVolumeClaim:
          claimName: my-workbench-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-workbench-pvc
  namespace: ml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: lvms-vg1
